#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server:
# Accepts 4 parameters
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# scp must transfer the file to the user home directory ~/
if [ $# -lt 4 ]
then
 echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
