#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get update
apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
place_holder="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _;/a $place_holder/" /etc/nginx/sites-enabled/default
service nginx start
