#!/usr/bin/python3
"""a python script to gather employee data from an API"""
import requests
import sys


def get_employee_todo(employee_id):
    """get employee data"""

    base_url = "https://jsonplaceholder.typicode.com"
    employee_url = f"{base_url}/users/{employee_id}"
    todos_url = f"{base_url}/todos?userId={employee_id}"

    employee_response = requests.get(employee_url)
    employee_data = employee_response.json()
    employee_name = employee_data.get("name")

    todos_response = requests.get(todos_url)
    todos = todos_response.json()

    finished_tasks = [task for task in todos if task["completed"]]
    num_finished_tasks = len(finished_tasks)
    total_tasks = len(todos)

    print(f"Employee {employee_name} is done with tasks
        ({num_finished_tasks}/{total_tasks}): ")
    for task in finished_tasks:
        print(f"\t{task['title']}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python script.py <employee_id>")
        sys.exit(1)

    employee_id = sys.argv[1]

    try:
        employee_id = int(employee_id)
    except ValueError:
        print("Employee ID must be an integer.")
        sys.exit(1)

    get_employee_todo(employee_id)
