#!/usr/bin/env bash
# debug the nginx server to listen to port 80

rm /etc/nginx/sites-enabled/default§
sudo ln -fs /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
