#!/usr/bin/env bash
# This script prints "Best School" with a while loop.

BestSchool=0  # Initialize the counter variable

while [ $BestSchool -le 9 ]
do
    echo "Best School $BestSchool"
    ((BestSchool++))  # Increment the counter variable
done
