#!/usr/bin/env bash
# This script print Best school using an until loop

count=0  # Initialize a counter variable

until [ $count -gt 9 ]
 do
    echo "Best School"
    (( count++ ))  # Increment the counter variable
done
