#!/usr/bin/env bash
# This script demonstrates printing "Best School" using a while loop and an if statement together

counter=0

while [ $counter -lt 10 ]
do
    echo "Best School"

    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi

    ((counter++))
done
