#!/usr/bin/env bash
# This script demonstrates printing "Best School" using a while loop and an if, elif and else statements

counter=1

while [ $counter -le 10 ]
do

    if [ $counter -eq]
    then
        echo "bad luck"
    elif [ $counter -eq 8]
   	echo "good luck"
    else
	echo "Best School"
    fi

    ((counter++))
done

