#!/usr/bin/env bash
# This script changes the resolution of localhost and facebook.com
# on an Ubuntu

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
